### ISSUE TITLE
getConfig will not run

### ISSUE THREAD

**Issue by Ken-B** [mitya57/python-markdown-math#4]
First of all, thank you very much for sharing this code.

I have a problem with line 37. 
```
  File "C:\Coding\Anaconda3\lib\site-packages\markdown\extensions\math.py", line
 37, in extendMarkdown
    configs = self.getConfigs()
  File "C:\Coding\Anaconda3\lib\site-packages\markdown\extensions\__init__.py",
line 28, in getConfigs
    return dict([(key, self.getConfig(key)) for key in self.config.keys()])
AttributeError: 'dict_items' object has no attribute 'keys'
```
If I comment out this line and lines 47-48 then mkdocs works fine and displays mathjax.
I'm on python 3.4.1.

**Comment by mitya57** [comment]
What version of Python-Markdown do you have? Can you try with the latest version (2.6.x)?

**Comment by Ken-B** [comment]
After upgrading to 2.6.2 I no longer get the error, good suggestion!

However, now it does not seem to use the configuration in my mkdocs.yml:
```
markdown_extensions: 
    math:
        enable_dollar_delimiter: True
```
because my inline math with $ signs are not caught. Am I using the right configuration?

**Comment by mitya57** [comment]
Try changing `math` to `mdx_math`.
